### ISSUE TITLE
Issue Create New Environment 

### ISSUE THREAD

**Issue by gabriansa** [Healthcare-Robotics/assistive-gym#19]
Hello,

I was following the ["6. Creating a New Assistive Environment"](https://github.com/Healthcare-Robotics/assistive-gym/wiki/6.-Creating-a-New-Assistive-Environment) tutorial on the wiki page.

However, when I get to the end and I try to train the model with the following command I get an error (I am working in a virtual env):

Command 1 
```python3 -m ppo.train --env-name "ReachingJaco-v0" --num-env-steps 1000000 --save-dir ./trained_models_new/```

ERROR: 
```/home/gabrigoo/Assistive Gym Stuff/env/bin/python3: No module named ppo.train```

I also tried the following command and I get this error:

Command 2: 
```python3 -m assistive_gym --env "ReachingJaco-v0"```

ERROR:
```
pybullet build time: Oct 14 2021 09:51:13
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gabrigoo/Assistive Gym Stuff/assistive-gym/assistive_gym/__main__.py", line 10, in <module>
    viewer(args.env)
  File "/home/gabrigoo/Assistive Gym Stuff/assistive-gym/assistive_gym/env_viewer.py", line 17, in viewer
    env = make_env(env_name, coop=True) if coop else gym.make(env_name)
  File "/home/gabrigoo/Assistive Gym Stuff/env/lib/python3.8/site-packages/gym/envs/registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "/home/gabrigoo/Assistive Gym Stuff/env/lib/python3.8/site-packages/gym/envs/registration.py", line 129, in make
    env = spec.make(**kwargs)
  File "/home/gabrigoo/Assistive Gym Stuff/env/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
    env = cls(**_kwargs)
  File "/home/gabrigoo/Assistive Gym Stuff/assistive-gym/assistive_gym/envs/reaching_robots.py", line 8, in __init__
    super(ReachingJacoEnv, self).__init__(robot_type='jaco', human_control=False)
  File "/home/gabrigoo/Assistive Gym Stuff/assistive-gym/assistive_gym/envs/reaching.py", line 9, in __init__
    super(ReachingEnv, self).__init__(robot_type=robot_type, task='reaching', human_control=human_control, frame_skip=5, time_step=0.02, action_robot_len=7, action_human_len=(4 if human_control else 0), obs_robot_len=21, obs_human_len=(19 if human_control else 0))
TypeError: __init__() got an unexpected keyword argument 'robot_type'
```
Any idea why this happens and what is the cause?
Thanks in advance for your help

After some tweaking, I think the issue stands from the fact that the tutorial is for version 0.1 while I am running version 1. Do you think the wiki could be updated for the newer version?

**Comment by gabriansa** [comment]
Here is the tutorial for the new version:

https://colab.research.google.com/drive/14du2mGdnVNPoN1woxLOpwtEU6HJFYCPg?usp=sharing#scrollTo=wIWxEauxcV3T
